# Generated by Django 4.2 on 2023-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[(0, 'Fall'), (1, 'Spring'), (2, 'Summer')], default=1, max_length=9)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
